language: python
sudo: false
dist: xenial
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
env:
  - DJANGO="Django~=1.11"
  - DJANGO="Django~=2.0"
  - DJANGO="Django~=2.1"
install:
  - pip install --quiet --upgrade -r requirements.txt
  - pip install --quiet --upgrade setuptools wheel
  - pip install --quiet --upgrade "$DJANGO"
script:
  - python -m pip install --upgrade pip setuptools wheel
  - inv test
  - inv build
  - inv test-install
  - inv coverage
after_success:
  - coveralls
notifications:
  email: false
