language: python
sudo: false
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "nightly" # currently points to 3.7-dev
env:
  - DJANGO="Django~=1.11"   # Django 1.11  (LTS version)
  - DJANGO="Django~=2.0"    # Django 2.0
install:
    - pip install --quiet --upgrade -r requirements.txt
    - pip install --quiet --upgrade setuptools wheel
    - pip install --quiet --upgrade "$DJANGO"
script:
    - python -m pip install -U pip
    - inv test
    - inv build
    - inv test_install
    - inv coverage
after_success:
    - coveralls
notifications:
    email: false
