language: python
sudo: false
python:
  - 3.4
  - 3.5
  - "3.6-dev"   # 3.6 development branch
  - "nightly"   # currently points to 3.7-dev
env:
  - DJANGO="Django<1.9"   # Django 1.8.x (LTS version)  |   2.7, 3.2 (until the end of 2016), 3.3, 3.4, 3.5
  - DJANGO="Django<1.10"  # Django 1.9.x                |   2.7, 3.4, 3.5
  - DJANGO="Django<1.11"  # Django 1.10.x               |   2.7, 3.4, 3.5
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install typing; fi
    - pip install --quiet --upgrade -r requirements.txt
    - pip install --quiet --upgrade setuptools wheel
    - pip install --quiet --upgrade "$DJANGO"
script:
    - python -m pip install -U pip
    - inv test
    - inv build
    - inv test_install
    - inv coverage
after_success:
    - coveralls
notifications:
    email: false
